### ISSUE TITLE
Unable to load named entity extractor

### ISSUE THREAD

**Issue by akshay-vaidya** [nmstoker/lockebot#10]
I am using the pretrained model model_20170423-110538. I see the file exists in the below path but I am getting the below error.
Unable to load named entity extractor from ./models/model_20170423-110538/entity_extractor.dat
Please help fixing this issue.
Thanks!

**Comment by nmstoker** [comment]
Sorry @akshay-vaidya  I seem to have missed when you posted this earlier...

I suspect something is up with the configuration or the versions of MITIE and/or Rasa NLU that are installed, because it's normally only the file total_word_feature_extractor.dat that is needed, not entity_extractor.dat.  The steps I have for the installation here are for a slightly older version of Rasa NLU but it (Rasa NLU) has moved on a bit since this was written, so that may be causing the issue.

Could you confirm the module versions? (eg with pip list) Key ones to focus on are MITIE, rasa-nlu and scikit-learn.

**Comment by roysoham** [comment]
<<same error>>
PIP list
arrow (0.10.0)
beautifulsoup4 (4.4.1)
certifi (2017.11.5)
chardet (3.0.4)
click (6.6)
cloudpickle (0.5.1)
colored (1.3.3)
cymem (1.31.2)
Flask (0.11.1)
gunicorn (19.6.0)
html5lib (0.999)
idna (2.6)
imaplib2 (2.45.0)
itsdangerous (0.24)
Jinja2 (2.8)
lxml (3.5.0)
MarkupSafe (0.23)
mercurial (3.7.3)
mitie (0.2.0)
murmurhash (0.26.4)
numpy (1.11.3)
pathlib (1.0.1)
pip (9.0.1)
plac (0.9.6)
preshed (0.46.4)
python-dateutil (2.6.1)
rasa-nlu (0.5.0.0)
requests (2.12.4)
roman (2.0.0)
scikit-learn (0.18.1)
scipy (0.18.1)
semver (2.7.9)
setuptools (20.7.0)
six (1.10.0)
spacy (1.4.0)
sputnik (0.9.3)
thinc (5.0.8)
ujson (1.35)
urllib3 (1.22)
Werkzeug (0.11.10)
wheel (0.29.0)

**Comment by roysoham** [comment]
resolved, paste the file "total_word_feature_extractor.dat"  in the exact sub folder MITIE/MITIE-models/english/total_word_feature_extractor.dat

**Comment by nmstoker** [comment]
Okay. Thanks for the update. I'll close this now
