### ISSUE TITLE
MITIEInterpreter issue

### ISSUE THREAD

**Issue by AfrahAsif** [nmstoker/lockebot#13]
OS: windows 8.1, 64-bit
MITIE version 0.5.0
rasa_nlu version 0.13.8
Rasa core version 0.11.2
Python 3.6.3

With the backend, mitie_sklearn, and for the following line of code,
from rasa_nlu.interpreters.mitie_interpreter import MITIEInterpreter

The error shows as
ModuleNotFoundError: No module named rasa_nlu.interpreters

which I rectified using the code,
from rasa_nlu.model import Interpreter

But how to resolve the error, 
ModuleNotFoundError: No module named MITIEInterpreter ?

**Comment by nmstoker** [comment]
Hi @AfrahAsif - thanks for the details and sorry you're having a problem with the code.  I believe it's because you're on a much newer version of Rasa NLU and the repo is for a much earlier version as per the requirements.txt file (eg 0.5.0.0)

Using MITIE was actually something of a pain and I think generally Rasa hasn't pushed to use it for a while now, so it might be best to switch the code to use one of the other options for NER - I haven't updated the code for a bit but it shouldn't be too hard to do.  Alternatively if you downgrade Rasa NLU to 0.5 it should work (although I notice you're also on Windows and I didn't get round to testing on there)

Let me know how you get on :slightly_smiling_face:

**Comment by nmstoker** [comment]
With the recent code updates this should work now and it no longer uses MITIE.

Instructions in the README will be refined a bit more soon. Under Rasa 2.0 with Rasa X it operates a bit differently, it is run as an action server and with Rasa X / Rasa Run.
